Ktb 19 refactoring serialization
DenisGubernatorov/KotlinTelegramBot pull request #17
Opened 2024-11-04 13:57 UTC by DenisGubernatorov

2024-11-04 17:44 UTC, dzenonce requested changes
Не понятно, как выйти из режима обучения, если только не через `/start`. Давай добавим кнопку "В меню".

2024-11-04 17:44 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +    val json =
Давай `json` сделаем полем внутри `TelegramBotService()` и не будем передавать через методы. Ведь парсинг `json`-а это по сути задача сервиса, нам не важно в каком виде приходят данные от Telegram API.

2024-11-05 14:45 UTC, DenisGubernatorov commented
> Не понятно, как выйти из режима обучения, если только не через `/start`. Давай добавим кнопку "В меню".
Да. Дейстивтельно. Походу эту кнопку забыли реализовать для телеграмм бота. Я посмотрел уроки дальше, до дополнительных этапов. Там ничего такого нет.

2024-11-05 17:17 UTC, dzenonce approved these changes

2024-11-05 18:47 UTC, merged