KTB-06-statistic-mode
DenisGubernatorov/KotlinTelegramBot pull request #5
Opened 2024-09-23 20:54 UTC by DenisGubernatorov

1) Изменено правильное количество ответов для слов в словаре, для наглядности вывода вариантов ответа 2) learnedWords вынесено из when в область видимости основного цикла, для общего использования в when 3) Предварительный вариант вывода слов и вариантов для них. Выводит все неизученные слова, без ожидания пользователя ввода ответа. Реализовано в приватной функции

2024-09-23 21:00 UTC, DenisGubernatorov commented
В задаче написано: " Там говорится о том, что для вариантов ответа должно браться максимальное количество невыученных слов (чтобы пользователь не угадал их методом исключения)." При таком варианте, если невыученных слов будет только 1 или 2. То и вариантов ответа, соответственно будет 1 или 2. При таком количестве это противоречит тому, что бы пользователь не смог угадать методом исключения

2024-09-25 11:07 UTC, kaznikit commented
> В задаче написано: " Там говорится о том, что для вариантов ответа должно браться максимальное количество невыученных слов (чтобы пользователь не угадал их методом исключения)." При таком варианте, если невыученных слов будет только 1 или 2. То и вариантов ответа, соответственно будет 1 или 2. При таком количестве это противоречит тому, что бы пользователь не смог угадать методом исключения

в таком варианте мы должны докидывать варианты ответа из списка уже выученных слов, чтобы у нас в сумме всегда было 4 варианта ответа

2024-09-25 11:09 UTC, kaznikit commented
> 1. Изменено правильное количество ответов для слов в словаре, для наглядности вывода вариантов ответа 2) learnedWords вынесено из when в область видимости основного цикла, для общего использования в when 3) Предварительный вариант вывода слов и вариантов для них. Выводит все неизученные слова, без ожидания пользователя ввода ответа. Реализовано в приватной функции

будь внимательнее к номерам задач. у тебя ПР называется KTB-6, ветка KTB-7, при этом код тоже для KTB-7)

2024-09-25 11:12 UTC, kaznikit requested changes

2024-09-25 11:12 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +private fun studyStageIn(wordsToLearn: Set<Word>): Boolean {
функции нужно стараться называть в инфинитиве, тут больше подойдет `startLearning`

2024-09-25 11:12 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +            val variants = wordsToLearn.take(wordsToLearn.size).shuffled()
нужно добавить к списку выученные слова, чтобы в сумме было 4 варианта ответа

2024-09-25 11:12 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +    var isFinished = false
нам в целом ответ из функции не особо то и нужен) в случае когда мы выучили все слова юзер увидит об этом сообщение и сможет выбрать еще 1 пункт меню, например посмотреть статистику

2024-09-27 06:13 UTC, kaznikit approved these changes

2024-09-27 12:52 UTC, merged