KTB-09-refactoring
DenisGubernatorov/KotlinTelegramBot pull request #7
Opened 2024-09-30 21:33 UTC by DenisGubernatorov

Разнесение логики работы тренажера и вывода сообщений в консоль 1) Добавлен класс LearnWordTrainer с методами отвечающими за логику формирования статистки и вопросов 2) Добавлен дата класс Statistic отвечающий за хранение статистики во время клиентской сессии 3) Добавлен класс Question, отвечающий за создание вопроса

2024-10-02 07:48 UTC, kaznikit requested changes

2024-10-02 07:48 UTC, kaznikit commented on src/main/kotlin/LearnWordTrainer.kt
> +    val isEmptyQuestion: Boolean = false,
а для чего это поле если оно нигде не используется? давай удалим

2024-10-02 07:48 UTC, kaznikit commented on src/main/kotlin/LearnWordTrainer.kt
> +    private val wordsFile = File("words.txt")
давай название файла, количество правильных ответов для определения выучено ли слово (3) и вариантов ответа (4) вынесем в аргументы конструктора и дадим им дефолтные значения

2024-10-02 07:48 UTC, kaznikit commented on src/main/kotlin/LearnWordTrainer.kt
> +    private var wordsToLearn = updateWordsToLearn()
мне кажется этот список лучше получать заново в каждой из функций, так как он не будет изменяться после выполнения какой-либо из функций и есть вероятность что он будет устаревший

2024-10-02 19:49 UTC, DenisGubernatorov commented
В функции getAnswerVariants не стал обновлять список wordsToLearn, так его уже обновил в getQuestions

2024-10-03 13:40 UTC, kaznikit approved these changes

2024-10-03 19:44 UTC, merged